apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: wunder-weather
  region: us-east-2

nodeGroups:
  - name: EKS-public-workers
    instanceType: t2.medium
    desiredCapacity: 2
    ssh:
      publicKeyName: udacity
