apiVersion: apps/v1
kind: Deployment
metadata:
  name: wunder-weather-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wunder-weather-frontend
  template:
    metadata:
      labels:
        app: wunder-weather-frontend
    spec:
      containers:
      - name: wunder-weather-frontend
        image: danrhjones/wunder-weather:${$CIRCLE_BUILD_NUM}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
