apiVersion: apps/v1
kind: Deployment
metadata:
  name: wunderweather
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wunderweather
  template:
    metadata:
      labels:
        app: wunderweather
    spec:
      containers:
      - name: wunderweather
        image: danrhjones/wunder-weather:${$CIRCLE_BUILD_NUM}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
---
apiVersion: v1
kind: Service
metadata:
  name: wunderweather
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: wunderweather
